version: '3'
services:
  flask:
    build: .
    ports:
      - "5000:5000"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "7070:7070"
    depends_on:
      - flask
